# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task-delay-queue-service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task-delay-queue-service.proto',
  package='usherasnick.photon_dance_delay_queue',
  syntax='proto3',
  serialized_options=b'Z3github.com/usherasnick/Delay-Queue/api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1etask-delay-queue-service.proto\x12$usherasnick.photon_dance_delay_queue\"W\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x16\n\x0e\x61ttached_topic\x18\x02 \x01(\t\x12\r\n\x05\x64\x65lay\x18\x03 \x01(\x05\x12\x0b\n\x03ttr\x18\x04 \x01(\x05\x12\x0f\n\x07payload\x18\x05 \x01(\t\"K\n\x0fPushTaskRequest\x12\x38\n\x04task\x18\x01 \x01(\x0b\x32*.usherasnick.photon_dance_delay_queue.Task\"\x12\n\x10PushTaskResponse\"$\n\x11\x46inishTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x14\n\x12\x46inishTaskResponse\"#\n\x10\x43heckTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"M\n\x11\x43heckTaskResponse\x12\x38\n\x04task\x18\x01 \x01(\x0b\x32*.usherasnick.photon_dance_delay_queue.Task\"&\n\x15SubscribeTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\x18\n\x16SubscribeTopicResponse\"(\n\x17UnsubscribeTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\x1a\n\x18UnsubscribeTopicResponse2\xb3\x05\n\x15TaskDelayQueueService\x12y\n\x08PushTask\x12\x35.usherasnick.photon_dance_delay_queue.PushTaskRequest\x1a\x36.usherasnick.photon_dance_delay_queue.PushTaskResponse\x12\x7f\n\nFinishTask\x12\x37.usherasnick.photon_dance_delay_queue.FinishTaskRequest\x1a\x38.usherasnick.photon_dance_delay_queue.FinishTaskResponse\x12|\n\tCheckTask\x12\x36.usherasnick.photon_dance_delay_queue.CheckTaskRequest\x1a\x37.usherasnick.photon_dance_delay_queue.CheckTaskResponse\x12\x8b\x01\n\x0eSubscribeTopic\x12;.usherasnick.photon_dance_delay_queue.SubscribeTopicRequest\x1a<.usherasnick.photon_dance_delay_queue.SubscribeTopicResponse\x12\x91\x01\n\x10UnsubscribeTopic\x12=.usherasnick.photon_dance_delay_queue.UnsubscribeTopicRequest\x1a>.usherasnick.photon_dance_delay_queue.UnsubscribeTopicResponseB5Z3github.com/usherasnick/Delay-Queue/apib\x06proto3'
)




_TASK = _descriptor.Descriptor(
  name='Task',
  full_name='usherasnick.photon_dance_delay_queue.Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='usherasnick.photon_dance_delay_queue.Task.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attached_topic', full_name='usherasnick.photon_dance_delay_queue.Task.attached_topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='delay', full_name='usherasnick.photon_dance_delay_queue.Task.delay', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ttr', full_name='usherasnick.photon_dance_delay_queue.Task.ttr', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='usherasnick.photon_dance_delay_queue.Task.payload', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=159,
)


_PUSHTASKREQUEST = _descriptor.Descriptor(
  name='PushTaskRequest',
  full_name='usherasnick.photon_dance_delay_queue.PushTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='usherasnick.photon_dance_delay_queue.PushTaskRequest.task', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=236,
)


_PUSHTASKRESPONSE = _descriptor.Descriptor(
  name='PushTaskResponse',
  full_name='usherasnick.photon_dance_delay_queue.PushTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=256,
)


_FINISHTASKREQUEST = _descriptor.Descriptor(
  name='FinishTaskRequest',
  full_name='usherasnick.photon_dance_delay_queue.FinishTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='usherasnick.photon_dance_delay_queue.FinishTaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=294,
)


_FINISHTASKRESPONSE = _descriptor.Descriptor(
  name='FinishTaskResponse',
  full_name='usherasnick.photon_dance_delay_queue.FinishTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=296,
  serialized_end=316,
)


_CHECKTASKREQUEST = _descriptor.Descriptor(
  name='CheckTaskRequest',
  full_name='usherasnick.photon_dance_delay_queue.CheckTaskRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='usherasnick.photon_dance_delay_queue.CheckTaskRequest.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=318,
  serialized_end=353,
)


_CHECKTASKRESPONSE = _descriptor.Descriptor(
  name='CheckTaskResponse',
  full_name='usherasnick.photon_dance_delay_queue.CheckTaskResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='task', full_name='usherasnick.photon_dance_delay_queue.CheckTaskResponse.task', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=432,
)


_SUBSCRIBETOPICREQUEST = _descriptor.Descriptor(
  name='SubscribeTopicRequest',
  full_name='usherasnick.photon_dance_delay_queue.SubscribeTopicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='usherasnick.photon_dance_delay_queue.SubscribeTopicRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=472,
)


_SUBSCRIBETOPICRESPONSE = _descriptor.Descriptor(
  name='SubscribeTopicResponse',
  full_name='usherasnick.photon_dance_delay_queue.SubscribeTopicResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=498,
)


_UNSUBSCRIBETOPICREQUEST = _descriptor.Descriptor(
  name='UnsubscribeTopicRequest',
  full_name='usherasnick.photon_dance_delay_queue.UnsubscribeTopicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='usherasnick.photon_dance_delay_queue.UnsubscribeTopicRequest.topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=540,
)


_UNSUBSCRIBETOPICRESPONSE = _descriptor.Descriptor(
  name='UnsubscribeTopicResponse',
  full_name='usherasnick.photon_dance_delay_queue.UnsubscribeTopicResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=568,
)

_PUSHTASKREQUEST.fields_by_name['task'].message_type = _TASK
_CHECKTASKRESPONSE.fields_by_name['task'].message_type = _TASK
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['PushTaskRequest'] = _PUSHTASKREQUEST
DESCRIPTOR.message_types_by_name['PushTaskResponse'] = _PUSHTASKRESPONSE
DESCRIPTOR.message_types_by_name['FinishTaskRequest'] = _FINISHTASKREQUEST
DESCRIPTOR.message_types_by_name['FinishTaskResponse'] = _FINISHTASKRESPONSE
DESCRIPTOR.message_types_by_name['CheckTaskRequest'] = _CHECKTASKREQUEST
DESCRIPTOR.message_types_by_name['CheckTaskResponse'] = _CHECKTASKRESPONSE
DESCRIPTOR.message_types_by_name['SubscribeTopicRequest'] = _SUBSCRIBETOPICREQUEST
DESCRIPTOR.message_types_by_name['SubscribeTopicResponse'] = _SUBSCRIBETOPICRESPONSE
DESCRIPTOR.message_types_by_name['UnsubscribeTopicRequest'] = _UNSUBSCRIBETOPICREQUEST
DESCRIPTOR.message_types_by_name['UnsubscribeTopicResponse'] = _UNSUBSCRIBETOPICRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Task = _reflection.GeneratedProtocolMessageType('Task', (_message.Message,), {
  'DESCRIPTOR' : _TASK,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.Task)
  })
_sym_db.RegisterMessage(Task)

PushTaskRequest = _reflection.GeneratedProtocolMessageType('PushTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHTASKREQUEST,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.PushTaskRequest)
  })
_sym_db.RegisterMessage(PushTaskRequest)

PushTaskResponse = _reflection.GeneratedProtocolMessageType('PushTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUSHTASKRESPONSE,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.PushTaskResponse)
  })
_sym_db.RegisterMessage(PushTaskResponse)

FinishTaskRequest = _reflection.GeneratedProtocolMessageType('FinishTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINISHTASKREQUEST,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.FinishTaskRequest)
  })
_sym_db.RegisterMessage(FinishTaskRequest)

FinishTaskResponse = _reflection.GeneratedProtocolMessageType('FinishTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _FINISHTASKRESPONSE,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.FinishTaskResponse)
  })
_sym_db.RegisterMessage(FinishTaskResponse)

CheckTaskRequest = _reflection.GeneratedProtocolMessageType('CheckTaskRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKTASKREQUEST,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.CheckTaskRequest)
  })
_sym_db.RegisterMessage(CheckTaskRequest)

CheckTaskResponse = _reflection.GeneratedProtocolMessageType('CheckTaskResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKTASKRESPONSE,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.CheckTaskResponse)
  })
_sym_db.RegisterMessage(CheckTaskResponse)

SubscribeTopicRequest = _reflection.GeneratedProtocolMessageType('SubscribeTopicRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBETOPICREQUEST,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.SubscribeTopicRequest)
  })
_sym_db.RegisterMessage(SubscribeTopicRequest)

SubscribeTopicResponse = _reflection.GeneratedProtocolMessageType('SubscribeTopicResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBETOPICRESPONSE,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.SubscribeTopicResponse)
  })
_sym_db.RegisterMessage(SubscribeTopicResponse)

UnsubscribeTopicRequest = _reflection.GeneratedProtocolMessageType('UnsubscribeTopicRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNSUBSCRIBETOPICREQUEST,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.UnsubscribeTopicRequest)
  })
_sym_db.RegisterMessage(UnsubscribeTopicRequest)

UnsubscribeTopicResponse = _reflection.GeneratedProtocolMessageType('UnsubscribeTopicResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNSUBSCRIBETOPICRESPONSE,
  '__module__' : 'task_delay_queue_service_pb2'
  # @@protoc_insertion_point(class_scope:usherasnick.photon_dance_delay_queue.UnsubscribeTopicResponse)
  })
_sym_db.RegisterMessage(UnsubscribeTopicResponse)


DESCRIPTOR._options = None

_TASKDELAYQUEUESERVICE = _descriptor.ServiceDescriptor(
  name='TaskDelayQueueService',
  full_name='usherasnick.photon_dance_delay_queue.TaskDelayQueueService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=571,
  serialized_end=1262,
  methods=[
  _descriptor.MethodDescriptor(
    name='PushTask',
    full_name='usherasnick.photon_dance_delay_queue.TaskDelayQueueService.PushTask',
    index=0,
    containing_service=None,
    input_type=_PUSHTASKREQUEST,
    output_type=_PUSHTASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FinishTask',
    full_name='usherasnick.photon_dance_delay_queue.TaskDelayQueueService.FinishTask',
    index=1,
    containing_service=None,
    input_type=_FINISHTASKREQUEST,
    output_type=_FINISHTASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckTask',
    full_name='usherasnick.photon_dance_delay_queue.TaskDelayQueueService.CheckTask',
    index=2,
    containing_service=None,
    input_type=_CHECKTASKREQUEST,
    output_type=_CHECKTASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeTopic',
    full_name='usherasnick.photon_dance_delay_queue.TaskDelayQueueService.SubscribeTopic',
    index=3,
    containing_service=None,
    input_type=_SUBSCRIBETOPICREQUEST,
    output_type=_SUBSCRIBETOPICRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UnsubscribeTopic',
    full_name='usherasnick.photon_dance_delay_queue.TaskDelayQueueService.UnsubscribeTopic',
    index=4,
    containing_service=None,
    input_type=_UNSUBSCRIBETOPICREQUEST,
    output_type=_UNSUBSCRIBETOPICRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TASKDELAYQUEUESERVICE)

DESCRIPTOR.services_by_name['TaskDelayQueueService'] = _TASKDELAYQUEUESERVICE

# @@protoc_insertion_point(module_scope)
