// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: github.com/usherasnick/Delay-Queue/pb/task-delay-queue-service.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 任务唯一标识, 用来检索/删除指定的任务
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 任务类型, 可以是具体的业务名称
	AttachedTopic string `protobuf:"bytes,2,opt,name=attached_topic,json=attachedTopic,proto3" json:"attached_topic,omitempty"`
	// 任务需要延迟执行的时间, 单位: 秒
	Delay int32 `protobuf:"varint,3,opt,name=delay,proto3" json:"delay,omitempty"`
	// 任务执行超时的时间, 单位: 秒
	Ttr int32 `protobuf:"varint,4,opt,name=ttr,proto3" json:"ttr,omitempty"`
	// 任务内容, 供消费者做具体的业务处理, 以json格式存储
	Payload string `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetAttachedTopic() string {
	if x != nil {
		return x.AttachedTopic
	}
	return ""
}

func (x *Task) GetDelay() int32 {
	if x != nil {
		return x.Delay
	}
	return 0
}

func (x *Task) GetTtr() int32 {
	if x != nil {
		return x.Ttr
	}
	return 0
}

func (x *Task) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type PushTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *PushTaskRequest) Reset() {
	*x = PushTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTaskRequest) ProtoMessage() {}

func (x *PushTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTaskRequest.ProtoReflect.Descriptor instead.
func (*PushTaskRequest) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{1}
}

func (x *PushTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type PushTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PushTaskResponse) Reset() {
	*x = PushTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PushTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushTaskResponse) ProtoMessage() {}

func (x *PushTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushTaskResponse.ProtoReflect.Descriptor instead.
func (*PushTaskResponse) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{2}
}

type FinishTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *FinishTaskRequest) Reset() {
	*x = FinishTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskRequest) ProtoMessage() {}

func (x *FinishTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskRequest.ProtoReflect.Descriptor instead.
func (*FinishTaskRequest) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{3}
}

func (x *FinishTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type FinishTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishTaskResponse) Reset() {
	*x = FinishTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTaskResponse) ProtoMessage() {}

func (x *FinishTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTaskResponse.ProtoReflect.Descriptor instead.
func (*FinishTaskResponse) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{4}
}

type CheckTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TaskId string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
}

func (x *CheckTaskRequest) Reset() {
	*x = CheckTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTaskRequest) ProtoMessage() {}

func (x *CheckTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTaskRequest.ProtoReflect.Descriptor instead.
func (*CheckTaskRequest) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CheckTaskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Task *Task `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
}

func (x *CheckTaskResponse) Reset() {
	*x = CheckTaskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckTaskResponse) ProtoMessage() {}

func (x *CheckTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckTaskResponse.ProtoReflect.Descriptor instead.
func (*CheckTaskResponse) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type SubscribeTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{7}
}

func (x *SubscribeTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type SubscribeTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SubscribeTopicResponse) Reset() {
	*x = SubscribeTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicResponse) ProtoMessage() {}

func (x *SubscribeTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicResponse.ProtoReflect.Descriptor instead.
func (*SubscribeTopicResponse) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{8}
}

type UnsubscribeTopicRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *UnsubscribeTopicRequest) Reset() {
	*x = UnsubscribeTopicRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeTopicRequest) ProtoMessage() {}

func (x *UnsubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*UnsubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{9}
}

func (x *UnsubscribeTopicRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type UnsubscribeTopicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnsubscribeTopicResponse) Reset() {
	*x = UnsubscribeTopicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnsubscribeTopicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeTopicResponse) ProtoMessage() {}

func (x *UnsubscribeTopicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeTopicResponse.ProtoReflect.Descriptor instead.
func (*UnsubscribeTopicResponse) Descriptor() ([]byte, []int) {
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP(), []int{10}
}

var File_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto protoreflect.FileDescriptor

var file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDesc = []byte{
	0x0a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x2d, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x2f, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x2d, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x2d,
	0x71, 0x75, 0x65, 0x75, 0x65, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x24, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77,
	0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65,
	0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x22, 0x7f, 0x0a, 0x04, 0x54, 0x61, 0x73,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x61, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x74, 0x74, 0x61, 0x63,
	0x68, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x14, 0x0a, 0x05, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x74, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x74, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x51, 0x0a, 0x0f, 0x50, 0x75,
	0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3e, 0x0a,
	0x04, 0x74, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x6d,
	0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e,
	0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x12, 0x0a,
	0x10, 0x50, 0x75, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x2c, 0x0a, 0x11, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x22,
	0x14, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2b, 0x0a, 0x10, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x61, 0x73,
	0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x73, 0x6b,
	0x49, 0x64, 0x22, 0x53, 0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63,
	0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65,
	0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x04, 0x74, 0x61, 0x73, 0x6b, 0x22, 0x2d, 0x0a, 0x15, 0x53, 0x75, 0x62, 0x73, 0x63,
	0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x2f, 0x0a, 0x17, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb3, 0x05,
	0x0a, 0x15, 0x54, 0x61, 0x73, 0x6b, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x51, 0x75, 0x65, 0x75, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x79, 0x0a, 0x08, 0x50, 0x75, 0x73, 0x68, 0x54,
	0x61, 0x73, 0x6b, 0x12, 0x35, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f,
	0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54,
	0x61, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75,
	0x65, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x7f, 0x0a, 0x0a, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x37, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x38, 0x2e, 0x61, 0x6d, 0x61, 0x7a,
	0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65,
	0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x7c, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x36, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70,
	0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x61,
	0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69,
	0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61,
	0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x61, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x8b, 0x01, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x3b, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68,
	0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x3c, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e,
	0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6c,
	0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69,
	0x62, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x91, 0x01, 0x0a, 0x10, 0x55, 0x6e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x12, 0x3d, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68,
	0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f,
	0x64, 0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x55, 0x6e, 0x73, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x3e, 0x2e, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f,
	0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x5f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2e, 0x55, 0x6e, 0x73, 0x75, 0x62,
	0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68,
	0x6f, 0x74, 0x6f, 0x6e, 0x2d, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x64, 0x65, 0x6c, 0x61, 0x79,
	0x2d, 0x71, 0x75, 0x65, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescOnce sync.Once
	file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescData = file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDesc
)

func file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescGZIP() []byte {
	file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescOnce.Do(func() {
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescData)
	})
	return file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDescData
}

var file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_goTypes = []interface{}{
	(*Task)(nil),                     // 0: usherasnick.photon_dance_delay_queue.Task
	(*PushTaskRequest)(nil),          // 1: usherasnick.photon_dance_delay_queue.PushTaskRequest
	(*PushTaskResponse)(nil),         // 2: usherasnick.photon_dance_delay_queue.PushTaskResponse
	(*FinishTaskRequest)(nil),        // 3: usherasnick.photon_dance_delay_queue.FinishTaskRequest
	(*FinishTaskResponse)(nil),       // 4: usherasnick.photon_dance_delay_queue.FinishTaskResponse
	(*CheckTaskRequest)(nil),         // 5: usherasnick.photon_dance_delay_queue.CheckTaskRequest
	(*CheckTaskResponse)(nil),        // 6: usherasnick.photon_dance_delay_queue.CheckTaskResponse
	(*SubscribeTopicRequest)(nil),    // 7: usherasnick.photon_dance_delay_queue.SubscribeTopicRequest
	(*SubscribeTopicResponse)(nil),   // 8: usherasnick.photon_dance_delay_queue.SubscribeTopicResponse
	(*UnsubscribeTopicRequest)(nil),  // 9: usherasnick.photon_dance_delay_queue.UnsubscribeTopicRequest
	(*UnsubscribeTopicResponse)(nil), // 10: usherasnick.photon_dance_delay_queue.UnsubscribeTopicResponse
}
var file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_depIdxs = []int32{
	0,  // 0: usherasnick.photon_dance_delay_queue.PushTaskRequest.task:type_name -> usherasnick.photon_dance_delay_queue.Task
	0,  // 1: usherasnick.photon_dance_delay_queue.CheckTaskResponse.task:type_name -> usherasnick.photon_dance_delay_queue.Task
	1,  // 2: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.PushTask:input_type -> usherasnick.photon_dance_delay_queue.PushTaskRequest
	3,  // 3: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.FinishTask:input_type -> usherasnick.photon_dance_delay_queue.FinishTaskRequest
	5,  // 4: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.CheckTask:input_type -> usherasnick.photon_dance_delay_queue.CheckTaskRequest
	7,  // 5: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.SubscribeTopic:input_type -> usherasnick.photon_dance_delay_queue.SubscribeTopicRequest
	9,  // 6: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.UnsubscribeTopic:input_type -> usherasnick.photon_dance_delay_queue.UnsubscribeTopicRequest
	2,  // 7: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.PushTask:output_type -> usherasnick.photon_dance_delay_queue.PushTaskResponse
	4,  // 8: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.FinishTask:output_type -> usherasnick.photon_dance_delay_queue.FinishTaskResponse
	6,  // 9: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.CheckTask:output_type -> usherasnick.photon_dance_delay_queue.CheckTaskResponse
	8,  // 10: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.SubscribeTopic:output_type -> usherasnick.photon_dance_delay_queue.SubscribeTopicResponse
	10, // 11: usherasnick.photon_dance_delay_queue.TaskDelayQueueService.UnsubscribeTopic:output_type -> usherasnick.photon_dance_delay_queue.UnsubscribeTopicResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() {
	file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_init()
}
func file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_init() {
	if File_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PushTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FinishTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckTaskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribeTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeTopicRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnsubscribeTopicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_goTypes,
		DependencyIndexes: file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_depIdxs,
		MessageInfos:      file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_msgTypes,
	}.Build()
	File_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto = out.File
	file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_rawDesc = nil
	file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_goTypes = nil
	file_github_com_usherasnick_photon_dance_delay_queue_pb_task_delay_queue_service_proto_depIdxs = nil
}
